// Code generated by command: go run asm.go -pkg loopVsBinarySearch -out lookup_amd64.s -stubs lookup_stub_amd64.go. DO NOT EDIT.

package loopVsBinarySearch

// Lookup returns the index into the array 'x' of the value 'k', or -1 if its not there. If k appears at multiple locations, you'll get one of them as the return value, it may not be the first one.
//go:noescape
func Lookup(k byte, x *[16]byte) int32
