// Code generated by command: go run asm.go -pkg loopVsBinarySearch -out lookup_amd64.s -stubs lookup_stub_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func Lookup(k byte, x *[16]byte) int32
// Requires: AVX2, BMI, SSE, SSE2
TEXT ·Lookup(SB), NOSPLIT, $0-20
	MOVQ         x+8(FP), AX
	MOVBLZX      k+0(FP), CX
	MOVD         CX, X0
	VPBROADCASTB X0, X0
	MOVUPD       (AX), X1
	PCMPEQB      X0, X1
	XORQ         CX, CX
	MOVQ         X1, AX
	TESTQ        AX, AX
	JNZ          returnCount
	MOVHLPS      X1, X1
	MOVQ         X1, AX
	TESTQ        AX, AX
	JZ           notFound
	MOVQ         $0x0000000000000008, CX

returnCount:
	TZCNTQ AX, AX
	SHRQ   $0x03, AX
	ADDQ   CX, AX
	MOVL   AX, ret+16(FP)
	RET

notFound:
	MOVL $0xffffffff, AX
	MOVL AX, ret+16(FP)
	RET
